name: "OpenAF's setup action"
description: "Setups OpenAF to be use in a GitHub action"
branding:
  icon : 'command'
  color: 'black'
inputs:
  dist:
    description: 'The OpenAF distribution to use'
    required: false
  version:
    description: 'A specific OpenAF version to use'
    required: false
runs:
  using: "composite"
  steps:
  # -------------------
  - name: Setup Java 21
    uses: actions/setup-java@v4
    with:
      java-version: 21
      distribution: 'temurin'

  # -------------------------------
  - name : Check for OpenAF runtime
    shell: bash
    run  : |
      if [ ! -f /tmp/oaf/oaf ]; then
        CDIR=`pwd`
        mkdir /tmp/oaf
        cd /tmp/oaf

        DIST=${{ inputs.dist }}
        DIST=$(echo "$DIST" | xargs)
        if [ "$DIST" = "stable" ]; then
          DIST=""
        fi

        VERSION=${{ inputs.version }}
        VERSION=$(echo "$VERSION" | xargs)
        if [ -n "$VERSION" ]; then
          VERSION="-$VERSION"
        else
          VERSION=""
        fi

        curl https://openaf.io/$DIST/openaf$VERSION.jar.repacked -o openaf.jar
        java -jar openaf.jar --install
        cd $CDIR
      fi
      for script in oaf oaf-sb oafp oafp-sb ojob ojob-sb opack openaf openaf-sb; do
        echo "Creating /usr/bin/$script..."
        echo -e "#!/bin/sh\n/tmp/oaf/$script \"\$@\"" | sudo tee /usr/bin/$script > /dev/null
        sudo chmod +x /usr/bin/$script
      done
