name: "OpenAF's setup action"
description: "Setups OpenAF to be use in a GitHub action"
branding:
  icon : 'command'
  color: 'black'
inputs:
  dist:
    description: 'The OpenAF distribution to use'
    required: false
runs:
  using: "composite"
  steps:
  # -------------------
  - name: Setup Java 21
    uses: actions/setup-java@v4
    with:
      java-version: 21
      distribution: 'temurin'
  - shell: bash
    name : Check for OpenAF runtime
    run  : |
      if [ ! -f /tmp/oaf/oaf ]; then
        CDIR=`pwd`
        mkdir /tmp/oaf
        cd /tmp/oaf
        curl https://openaf.io/${{ inputs.dist }}/openaf.jar.repacked -o openaf.jar
        java -jar openaf.jar --install
        cd $CDIR
      fi
      for script in oaf oaf-sb oafp oafp-sb ojob ojob-sb opack openaf openaf-sb; do
        echo "Creating /usr/bin/\$script..."
        echo -e "#!/bin/sh\n/tmp/oaf/\$script \"\$@\"" | sudo tee /usr/bin/\$script > /dev/null
        sudo chmod +x /usr/bin/\$script
      done
