name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
    - name: Check version
      run : |
        /tmp/oaf/oaf -v
    - name: Check version with symlink
      run : |
        oaf -v

  simple-test-with-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
      with:
        dist: nightly
    - name: Check version
      run : |
        /tmp/oaf/oaf -v
    - name: Check version with symlink
      run : |
        oaf -v

  oafp-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
    - name: Use oAFp
      run : |
        /tmp/oaf/oafp -v
    - name: Use oAFp with symlink
      run : |
        oafp -v

  readme-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
    - name: Show README
      run : |
        oafp README.md
    - name: Run README test
      run : |
        echo Summary table of number of files per extension:
        echo
        oafp data="." in=ls lsrecursive=true sql="select filepath, permissions, size where isFile=TRUE order by size desc" out=ctable