name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
    - name: Check version
      run : |
        /tmp/oaf/oaf -v
    - name: Check version with symlink
      run : |
        oaf -v

  test-with-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache OpenAF
      uses: actions/cache@v4
      with:
        key : oaf
        path: /tmp/oaf
    - name: Setup OpenAF
      uses: ./
    - name: Check version with symlink
      run : |
        oaf -v

  simple-test-with-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
      with:
        dist: nightly
    - name: Check version
      run : |
        /tmp/oaf/oaf -v
    - name: Check version with symlink
      run : |
        oaf -v

  oafp-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
    - name: Use oAFp
      run : |
        /tmp/oaf/oafp -v
    - name: Use oAFp with symlink
      run : |
        oafp -v

  readme-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
    - name: Show README
      run : |
        oafp README.md
    - name: Run README test
      run : |
        echo Summary table of number of files per extension:
        echo
        oafp data="." in=ls lsrecursive=true\
             sql="select filepath, permissions, size where isFile=TRUE order by size desc"\
             out=ctable

  opack-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
      with:
        opacks: oJob-common,GIST
    - name: List installed oPacks
      run : |
        opack list

  dist-version-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenAF
      uses: ./
      with:
        dist   : stable
        version: 20241117
    - name: Check OpenAF version and distribution
      run : |
        echo "The current OpenAF distribution is '$(oaf -c 'print(getDistribution())')'"
        echo "The current OpenAF version is '$(oaf -c 'print(getVersion())')'"